import UIKit

//You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:
//
//b[0] is equal to a[0];
//b[1] is equal to the last element of a;
//b[2] is equal to a[1];
//b[3] is equal to the second-last element of a;
//and so on

func alternatingSort(a: [Int]) -> Bool {
    var front = 0
    var back = a.count - 1
    var b = [Int]()
    
    guard !a.isEmpty else {
        return false
    }
    guard a.count > 1 else {
        return true
    }
    
    while b.count < a.count {
        b.append(a[front])
        b.append(a[back])
        if front != back {
            front += 1
            back -= 1
        } else {
            b.removeLast()
        }
    }
    print(b)
    
    return b == a.sorted()
}
var a = [-52, 2, 31, 56, 47, 29, -35]
//alternatingSort(a: a) //true
var a2 = [-91, -84, -67, -44, 9, 70, 88, 37, -11, -67, -72, -87]
alternatingSort(a: a2)//false
